object FormListen: TFormListen
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsNone
  Caption = 'Listen'
  ClientHeight = 304
  ClientWidth = 323
  Color = clBtnFace
  DoubleBuffered = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  Position = poOwnerFormCenter
  OnCreate = FormCreate
  OnKeyUp = FormKeyUp
  OnResize = FormResize
  OnShow = FormShow
  TextHeight = 14
  object PanelBottom: TFlatPanel
    Left = 0
    Top = 274
    Width = 323
    Height = 30
    Align = alBottom
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    BorderTop = 1
    BorderLeft = 0
    BorderRight = 0
    BorderBottom = 0
    Color = 13554645
    BorderColor = clBlack
    object ButtonConnect: TFlatButton
      Left = 208
      Top = 6
      Width = 80
      Height = 20
      Caption = 'Connect'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ShowHint = True
      ImageIndex = -1
      Value = 0
      OnClick = ButtonConnectClick
      Busy = False
    end
    object ButtonCancel: TFlatButton
      Left = 122
      Top = 6
      Width = 80
      Height = 20
      Caption = 'Cancel'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ShowHint = True
      ImageIndex = -1
      Value = 0
      OnClick = ButtonCancelClick
      Busy = False
    end
  end
  object PanelClient: TFlatPanel
    Left = 0
    Top = 0
    Width = 323
    Height = 274
    Align = alClient
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 1
    Padding.Left = 8
    Padding.Top = 8
    Padding.Right = 8
    Padding.Bottom = 8
    BorderTop = 0
    BorderLeft = 0
    BorderRight = 0
    BorderBottom = 0
    Color = 13554645
    BorderColor = clBlack
    object Label1: TLabel
      AlignWithMargins = True
      Left = 8
      Top = 156
      Width = 307
      Height = 13
      Margins.Left = 0
      Margins.Top = 4
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alTop
      Caption = 'Server Port:'
      ExplicitWidth = 59
    end
    object LabelCertificate: TLabel
      AlignWithMargins = True
      Left = 8
      Top = 218
      Width = 307
      Height = 13
      Margins.Left = 0
      Margins.Top = 4
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alTop
      Caption = 'Server Certificate:'
      ExplicitWidth = 89
    end
    object Label3: TLabel
      AlignWithMargins = True
      Left = 8
      Top = 8
      Width = 307
      Height = 13
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alTop
      Caption = 'IP Version:'
      ExplicitWidth = 52
    end
    object EditPort: TFlatEdit
      Left = 8
      Top = 169
      Width = 307
      Height = 24
      Align = alTop
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      MaxLength = 5
      NumbersOnly = True
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 0
      Text = '2801'
      OnChange = EditPortChange
      Status = cStatusNormal
      Validators = []
      ShowBorder = True
    end
    object ComboCertificate: TFlatComboBox
      Left = 8
      Top = 231
      Width = 307
      Height = 21
      Align = alTop
      Style = csDropDownList
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 1
      ItemIndex = -1
      Status = cStatusNormal
      Validators = []
    end
    object CheckBoxAutoStart: TFlatCheckBox
      AlignWithMargins = True
      Left = 8
      Top = 197
      Width = 307
      Height = 17
      Margins.Left = 0
      Margins.Top = 4
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alTop
      Caption = 'Automatically Start The Server.'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      Mode = cbmCheckBox
      Checked = True
    end
    object ComboIpVersion: TFlatComboBox
      Left = 8
      Top = 21
      Width = 307
      Height = 21
      Align = alTop
      Style = csDropDownList
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      Items.Strings = (
        'IPv4'
        'IPv6')
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 3
      Text = 'IPv4'
      ItemIndex = 0
      Status = cStatusNormal
      Validators = []
    end
    object GroupBox1: TFlatGroupBox
      AlignWithMargins = True
      Left = 8
      Top = 46
      Width = 307
      Height = 106
      Margins.Left = 0
      Margins.Top = 4
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alTop
      Caption = 'Bind Address:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      Color = 13554645
      Padding.Left = 8
      Padding.Top = 16
      Padding.Right = 8
      Padding.Bottom = 8
      ParentColor = False
      TabOrder = 4
      object RadioBindAll: TFlatCheckBox
        Left = 8
        Top = 16
        Width = 291
        Height = 17
        Align = alTop
        Caption = 'All Interfaces (Default)'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        Mode = cbmRadioBox
        Checked = True
        OnStateChanged = RadioBindLocalStateChanged
      end
      object RadioBindLocal: TFlatCheckBox
        Left = 8
        Top = 33
        Width = 291
        Height = 17
        Align = alTop
        Caption = 'Local host only'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        Mode = cbmRadioBox
        Checked = False
        OnStateChanged = RadioBindLocalStateChanged
      end
      object RadioBindCustom: TFlatCheckBox
        Left = 8
        Top = 50
        Width = 291
        Height = 17
        Align = alTop
        Caption = 'Custom:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        Mode = cbmRadioBox
        Checked = False
        OnStateChanged = RadioBindCustomStateChanged
      end
      object EditServerBindAddress: TFlatEdit
        AlignWithMargins = True
        Left = 26
        Top = 69
        Width = 273
        Height = 23
        Margins.Left = 18
        Margins.Top = 2
        Margins.Right = 0
        Margins.Bottom = 0
        Align = alTop
        AutoSize = False
        Color = clWhite
        Enabled = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clGray
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 3
        Status = cStatusNormal
        Validators = []
        ShowBorder = True
      end
    end
  end
  object FlatWindow1: TFlatWindow
    BorderWidth = 2
    CaptionHeight = 25
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    CaptionAlign = taLeftJustify
    ShowBorder = True
    BorderStyle = bsDialog
    Background = 13554645
    Border = clBlack
    Caption = clBlack
    Left = 241
    Top = 78
  end
end
