object ControlFormRegistryEditor: TControlFormRegistryEditor
  Left = 0
  Top = 0
  Caption = 'Registry Editor'
  ClientHeight = 533
  ClientWidth = 457
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  KeyPreview = True
  Position = poOwnerFormCenter
  OnClose = FormClose
  OnCreate = FormCreate
  OnKeyUp = FormKeyUp
  OnShow = FormShow
  TextHeight = 15
  object PanelMain: TFlatPanel
    Left = 0
    Top = 0
    Width = 457
    Height = 514
    Align = alClient
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    BorderTop = 0
    BorderLeft = 0
    BorderRight = 0
    BorderBottom = 0
    Color = 13554645
    BorderColor = clBlack
    object PanelHeader: TFlatPanel
      Left = 0
      Top = 0
      Width = 457
      Height = 48
      Align = alTop
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Padding.Left = 4
      Padding.Top = 4
      Padding.Right = 4
      Padding.Bottom = 4
      BorderTop = 0
      BorderLeft = 0
      BorderRight = 0
      BorderBottom = 1
      Color = 13554645
      BorderColor = clBlack
      object LabelName: TLabel
        AlignWithMargins = True
        Left = 4
        Top = 4
        Width = 31
        Height = 13
        Margins.Left = 0
        Margins.Top = 0
        Margins.Right = 0
        Margins.Bottom = 4
        Align = alTop
        Caption = 'Name:'
      end
      object EditName: TFlatEdit
        Left = 4
        Top = 21
        Width = 449
        Height = 16
        Align = alTop
        AutoSize = False
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 0
        OnKeyUp = EditNameKeyUp
        Status = cStatusNormal
        Validators = []
        ShowBorder = True
      end
    end
    object Notebook: TNotebook
      Left = 0
      Top = 48
      Width = 457
      Height = 430
      Align = alClient
      TabOrder = 1
      object TPage
        Left = 0
        Top = 0
        Caption = 'SZ'
        object PanelSZ: TPanel
          Left = 0
          Top = 0
          Width = 457
          Height = 430
          Align = alClient
          BevelOuter = bvNone
          Padding.Left = 4
          Padding.Top = 4
          Padding.Right = 4
          Padding.Bottom = 4
          TabOrder = 0
          object Label1: TLabel
            AlignWithMargins = True
            Left = 4
            Top = 4
            Width = 30
            Height = 13
            Margins.Left = 0
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 4
            Align = alTop
            Caption = 'Value:'
          end
          object EditSZ: TFlatEdit
            Left = 4
            Top = 21
            Width = 449
            Height = 16
            Align = alTop
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ShowHint = True
            TabOrder = 0
            OnKeyUp = EditNameKeyUp
            Status = cStatusNormal
            Validators = []
            ShowBorder = True
          end
        end
      end
      object TPage
        Left = 0
        Top = 0
        Caption = 'MSZ'
        object PanelMSZ: TPanel
          Left = 0
          Top = 0
          Width = 457
          Height = 430
          Align = alClient
          BevelOuter = bvNone
          Padding.Left = 4
          Padding.Top = 4
          Padding.Right = 4
          TabOrder = 0
          object Label2: TLabel
            AlignWithMargins = True
            Left = 4
            Top = 4
            Width = 30
            Height = 13
            Margins.Left = 0
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 4
            Align = alTop
            Caption = 'Value:'
          end
          object PanelRichMSZ: TFlatPanel
            AlignWithMargins = True
            Left = 4
            Top = 21
            Width = 449
            Height = 401
            Margins.Left = 0
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 8
            Align = alClient
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            TabOrder = 0
            Padding.Left = 1
            Padding.Top = 1
            Padding.Right = 1
            Padding.Bottom = 1
            BorderTop = 1
            BorderLeft = 1
            BorderRight = 1
            BorderBottom = 1
            Color = 13554645
            BorderColor = clBlack
            object RichMSZ: TRichEdit
              Left = 1
              Top = 1
              Width = 447
              Height = 399
              Align = alClient
              BevelOuter = bvNone
              BorderStyle = bsNone
              Font.Charset = ANSI_CHARSET
              Font.Color = clWindowText
              Font.Height = -12
              Font.Name = 'Segoe UI'
              Font.Style = []
              ParentFont = False
              ScrollBars = ssBoth
              TabOrder = 0
            end
          end
        end
      end
      object TPage
        Left = 0
        Top = 0
        Caption = 'DQWord'
        ExplicitWidth = 0
        ExplicitHeight = 0
        object PanelQDword: TPanel
          Left = 0
          Top = 0
          Width = 457
          Height = 430
          Align = alClient
          BevelOuter = bvNone
          Color = 13554645
          Padding.Left = 4
          Padding.Top = 4
          Padding.Right = 4
          Padding.Bottom = 4
          ParentBackground = False
          TabOrder = 0
          object Label3: TLabel
            AlignWithMargins = True
            Left = 4
            Top = 4
            Width = 30
            Height = 13
            Margins.Left = 0
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 4
            Align = alTop
            Caption = 'Value:'
          end
          object EditQDword: TFlatEdit
            Left = 4
            Top = 21
            Width = 449
            Height = 19
            Align = alTop
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ShowHint = True
            TabOrder = 0
            Text = '0'
            OnKeyPress = EditQDwordKeyPress
            Status = cStatusNormal
            Validators = []
            ShowBorder = True
          end
          object GroupBoxBase: TFlatGroupBox
            AlignWithMargins = True
            Left = 4
            Top = 48
            Width = 449
            Height = 77
            Margins.Left = 0
            Margins.Top = 8
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            Caption = 'Base'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            Color = 13554645
            Padding.Left = 8
            Padding.Top = 16
            Padding.Right = 8
            Padding.Bottom = 8
            ParentColor = False
            TabOrder = 1
            object RadioBaseDecimal: TFlatCheckBox
              Left = 8
              Top = 16
              Width = 433
              Height = 25
              Align = alTop
              Caption = 'Decimal'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clBlack
              Font.Height = -11
              Font.Name = 'Tahoma'
              Font.Style = []
              Mode = cbmRadioBox
              Checked = True
              OnStateChanged = RadioBaseDecimalStateChanged
            end
            object RadioBaseHexadecimal: TFlatCheckBox
              Left = 8
              Top = 41
              Width = 433
              Height = 25
              Align = alTop
              Caption = 'Hexadecimal'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clBlack
              Font.Height = -11
              Font.Name = 'Tahoma'
              Font.Style = []
              Mode = cbmRadioBox
              Checked = False
              OnStateChanged = RadioBaseHexadecimalStateChanged
            end
          end
        end
      end
      object TPage
        Left = 0
        Top = 0
        Caption = 'Binary'
        ExplicitWidth = 0
        ExplicitHeight = 0
        object PanelBinary: TPanel
          Left = 0
          Top = 0
          Width = 457
          Height = 430
          Align = alClient
          BevelOuter = bvNone
          TabOrder = 0
        end
      end
    end
    object PanelFooter: TFlatPanel
      Left = 0
      Top = 478
      Width = 457
      Height = 36
      Align = alBottom
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      BorderTop = 1
      BorderLeft = 0
      BorderRight = 0
      BorderBottom = 0
      Color = 13554645
      BorderColor = clBlack
      object ButtonAction: TFlatButton
        AlignWithMargins = True
        Left = 373
        Top = 8
        Width = 80
        Height = 22
        Margins.Top = 8
        Margins.Right = 4
        Margins.Bottom = 6
        Caption = 'XXX'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        Align = alRight
        ShowHint = True
        ImageIndex = -1
        Value = 0
        OnClick = ButtonActionClick
        Busy = False
        ExplicitLeft = 363
        ExplicitHeight = 25
      end
      object ButtonCancel: TFlatButton
        AlignWithMargins = True
        Left = 286
        Top = 8
        Width = 80
        Height = 22
        Margins.Left = 0
        Margins.Top = 8
        Margins.Right = 4
        Margins.Bottom = 6
        Caption = 'Cancel'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        Align = alRight
        ShowHint = True
        ImageIndex = -1
        Value = 0
        OnClick = ButtonCancelClick
        Busy = False
        ExplicitLeft = 266
        ExplicitHeight = 25
      end
    end
  end
  object StatusBar: TFlatStatusBar
    Left = 0
    Top = 514
    Width = 457
    Height = 19
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    Panels = <
      item
        Width = 200
        Alignment = taLeftJustify
      end>
  end
  object PopupMain: TFlatPopupMenu
    OwnerDraw = True
    Left = 136
    Top = 185
    object Switch2: TMenuItem
      Caption = 'Switch'
      object StringSZ1: TMenuItem
        Caption = 'String (SZ)'
        OnClick = StringSZ1Click
      end
      object MultiLineStringMSZ1: TMenuItem
        Caption = 'Multi Line String (MSZ)'
        OnClick = MultiLineStringMSZ1Click
      end
      object DWORD1: TMenuItem
        Caption = 'DWORD'
        OnClick = DWORD1Click
      end
      object QWORD1: TMenuItem
        Caption = 'QWORD'
        OnClick = QWORD1Click
      end
      object Binary1: TMenuItem
        Caption = 'Binary'
        OnClick = Binary1Click
      end
    end
  end
end
