object ControlFormSetupContentReader: TControlFormSetupContentReader
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  Caption = 'New Content Reader'
  ClientHeight = 126
  ClientWidth = 336
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  KeyPreview = True
  Position = poOwnerFormCenter
  OnClose = FormClose
  OnCreate = FormCreate
  OnKeyUp = FormKeyUp
  OnResize = FormResize
  OnShow = FormShow
  TextHeight = 15
  object PanelMain: TFlatPanel
    Left = 0
    Top = 0
    Width = 336
    Height = 91
    Align = alClient
    Caption = 'PanelMain'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    Padding.Left = 8
    Padding.Top = 4
    Padding.Right = 8
    BorderTop = 0
    BorderLeft = 0
    BorderRight = 0
    BorderBottom = 0
    Color = 13554645
    BorderColor = clBlack
    ExplicitWidth = 326
    ExplicitHeight = 77
    object PanelForm: TFlatPanel
      Left = 8
      Top = 4
      Width = 320
      Height = 87
      Align = alClient
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      BorderTop = 0
      BorderLeft = 0
      BorderRight = 0
      BorderBottom = 0
      Color = 13554645
      BorderColor = clBlack
      ExplicitLeft = 57
      ExplicitTop = 8
      ExplicitWidth = 261
      ExplicitHeight = 69
      object Label2: TLabel
        Left = 0
        Top = 0
        Width = 45
        Height = 13
        Align = alTop
        Caption = 'File Path:'
      end
      object LabelPageSize: TLabel
        AlignWithMargins = True
        Left = 0
        Top = 36
        Width = 46
        Height = 13
        Margins.Left = 0
        Margins.Top = 4
        Margins.Right = 0
        Margins.Bottom = 0
        Align = alTop
        Caption = 'Page Size'
      end
      object EditPath: TFlatEdit
        Left = 0
        Top = 13
        Width = 320
        Height = 19
        Align = alTop
        AutoSize = False
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 0
        Status = cStatusNormal
        Validators = []
        ShowBorder = True
        ExplicitLeft = 16
        ExplicitWidth = 245
      end
      object EditPageSize: TFlatEdit
        Left = 0
        Top = 49
        Width = 320
        Height = 19
        Align = alTop
        AutoSize = False
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        NumbersOnly = True
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 1
        Text = '1024'
        Status = cStatusNormal
        Validators = []
        ShowBorder = True
        ExplicitLeft = 16
        ExplicitWidth = 245
      end
    end
  end
  object PanelBottom: TFlatPanel
    Left = 0
    Top = 91
    Width = 336
    Height = 35
    Align = alBottom
    Caption = 'PanelBottom'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 1
    BorderTop = 1
    BorderLeft = 0
    BorderRight = 0
    BorderBottom = 0
    Color = 13554645
    BorderColor = clBlack
    ExplicitTop = 77
    ExplicitWidth = 326
    object ButtonCancel: TFlatButton
      Left = 136
      Top = 6
      Width = 65
      Height = 20
      Caption = 'Cancel'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ShowHint = True
      ImageIndex = -1
      Value = 0
      OnClick = ButtonCancelClick
      Busy = False
    end
    object ButtonStart: TFlatButton
      Left = 207
      Top = 12
      Width = 65
      Height = 20
      Caption = 'Start'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ShowHint = True
      ImageIndex = -1
      Value = 0
      OnClick = ButtonStartClick
      Busy = False
    end
  end
end
